spring:
  application:
    name: myconfig
  cloud:
    config:
      profile: dev
      uri: http://localhost:8888/
      enabled: true
      fail-fast: true
server:
  port: 8081
eureka:
  client:
    service-url:
      # nowork?
      defaultZone: http://localhost:8761/eureka/
    eureka-server-port: 8761
